// Static mapping of ISO 4217 currency codes to ISO 3166-1 alpha-2 country codes
// Used for flag-icons CSS class rendering: className="fi fi-{countryCode}"
export const CURRENCY_COUNTRY_MAP: Record<string, string> = {
  AUD: "au",
  BGN: "bg",
  BRL: "br",
  CAD: "ca",
  CHF: "ch",
  CNY: "cn",
  CZK: "cz",
  DKK: "dk",
  EUR: "eu",
  GBP: "gb",
  HKD: "hk",
  HUF: "hu",
  IDR: "id",
  ILS: "il",
  INR: "in",
  ISK: "is",
  JPY: "jp",
  KRW: "kr",
  MXN: "mx",
  MYR: "my",
  NOK: "no",
  NZD: "nz",
  PHP: "ph",
  PLN: "pl",
  RON: "ro",
  SEK: "se",
  SGD: "sg",
  THB: "th",
  TRY: "tr",
  USD: "us",
  ZAR: "za",
};

// Common currency display names for the picker
export const CURRENCY_NAMES: Record<string, string> = {
  AUD: "Australian Dollar",
  BGN: "Bulgarian Lev",
  BRL: "Brazilian Real",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  CZK: "Czech Koruna",
  DKK: "Danish Krone",
  EUR: "Euro",
  GBP: "British Pound",
  HKD: "Hong Kong Dollar",
  HUF: "Hungarian Forint",
  IDR: "Indonesian Rupiah",
  ILS: "Israeli Shekel",
  INR: "Indian Rupee",
  ISK: "Icelandic Krona",
  JPY: "Japanese Yen",
  KRW: "South Korean Won",
  MXN: "Mexican Peso",
  MYR: "Malaysian Ringgit",
  NOK: "Norwegian Krone",
  NZD: "New Zealand Dollar",
  PHP: "Philippine Peso",
  PLN: "Polish Zloty",
  RON: "Romanian Leu",
  SEK: "Swedish Krona",
  SGD: "Singapore Dollar",
  THB: "Thai Baht",
  TRY: "Turkish Lira",
  USD: "US Dollar",
  ZAR: "South African Rand",
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  AUD: "A$", BGN: "лв", BRL: "R$", CAD: "C$", CHF: "CHF", CNY: "¥",
  CZK: "Kč", DKK: "kr", EUR: "€", GBP: "£", HKD: "HK$", HUF: "Ft",
  IDR: "Rp", ILS: "₪", INR: "₹", ISK: "kr", JPY: "¥", KRW: "₩",
  MXN: "MX$", MYR: "RM", NOK: "kr", NZD: "NZ$", PHP: "₱", PLN: "zł",
  RON: "lei", SEK: "kr", SGD: "S$", THB: "฿", TRY: "₺", USD: "$",
  ZAR: "R",
};

export const ALL_CURRENCY_CODES = Object.keys(CURRENCY_COUNTRY_MAP).sort();
